package cn.edu.ken.mybatis.model;

public class ContactInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contactinfo.idcontactinfo
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private Integer idcontactinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contactinfo.contact_idcontact
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private Integer contactIdcontact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contactinfo.firstname
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private String firstname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contactinfo.secondname
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private String secondname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contactinfo.address
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contactinfo.state
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contactinfo.country
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contactinfo.city
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contactinfo.email
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contactinfo.telephone
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contactinfo.mobile
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private String mobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contactinfo.idcontactinfo
     *
     * @return the value of contactinfo.idcontactinfo
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public Integer getIdcontactinfo() {
        return idcontactinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contactinfo.idcontactinfo
     *
     * @param idcontactinfo the value for contactinfo.idcontactinfo
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setIdcontactinfo(Integer idcontactinfo) {
        this.idcontactinfo = idcontactinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contactinfo.contact_idcontact
     *
     * @return the value of contactinfo.contact_idcontact
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public Integer getContactIdcontact() {
        return contactIdcontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contactinfo.contact_idcontact
     *
     * @param contactIdcontact the value for contactinfo.contact_idcontact
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setContactIdcontact(Integer contactIdcontact) {
        this.contactIdcontact = contactIdcontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contactinfo.firstname
     *
     * @return the value of contactinfo.firstname
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contactinfo.firstname
     *
     * @param firstname the value for contactinfo.firstname
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contactinfo.secondname
     *
     * @return the value of contactinfo.secondname
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public String getSecondname() {
        return secondname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contactinfo.secondname
     *
     * @param secondname the value for contactinfo.secondname
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setSecondname(String secondname) {
        this.secondname = secondname == null ? null : secondname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contactinfo.address
     *
     * @return the value of contactinfo.address
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contactinfo.address
     *
     * @param address the value for contactinfo.address
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contactinfo.state
     *
     * @return the value of contactinfo.state
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contactinfo.state
     *
     * @param state the value for contactinfo.state
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contactinfo.country
     *
     * @return the value of contactinfo.country
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contactinfo.country
     *
     * @param country the value for contactinfo.country
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contactinfo.city
     *
     * @return the value of contactinfo.city
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contactinfo.city
     *
     * @param city the value for contactinfo.city
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contactinfo.email
     *
     * @return the value of contactinfo.email
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contactinfo.email
     *
     * @param email the value for contactinfo.email
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contactinfo.telephone
     *
     * @return the value of contactinfo.telephone
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contactinfo.telephone
     *
     * @param telephone the value for contactinfo.telephone
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contactinfo.mobile
     *
     * @return the value of contactinfo.mobile
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contactinfo.mobile
     *
     * @param mobile the value for contactinfo.mobile
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }
}