package cn.edu.ken.mybatis.mapper;

import cn.edu.ken.mybatis.model.Department;
import cn.edu.ken.mybatis.model.DepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @SelectProvider(type=DepartmentSqlProvider.class, method="countByExample")
    int countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @DeleteProvider(type=DepartmentSqlProvider.class, method="deleteByExample")
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @Delete({
        "delete from department",
        "where iddepartment = #{iddepartment,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer iddepartment);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @Insert({
        "insert into department (iddepartment, typecode, ",
        "typename, description, ",
        "priority, retired)",
        "values (#{iddepartment,jdbcType=INTEGER}, #{typecode,jdbcType=VARCHAR}, ",
        "#{typename,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{priority,jdbcType=VARCHAR}, #{retired,jdbcType=BIT})"
    })
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @InsertProvider(type=DepartmentSqlProvider.class, method="insertSelective")
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @SelectProvider(type=DepartmentSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="iddepartment", property="iddepartment", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="typecode", property="typecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="typename", property="typename", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="priority", property="priority", jdbcType=JdbcType.VARCHAR),
        @Result(column="retired", property="retired", jdbcType=JdbcType.BIT)
    })
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @Select({
        "select",
        "iddepartment, typecode, typename, description, priority, retired",
        "from department",
        "where iddepartment = #{iddepartment,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="iddepartment", property="iddepartment", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="typecode", property="typecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="typename", property="typename", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="priority", property="priority", jdbcType=JdbcType.VARCHAR),
        @Result(column="retired", property="retired", jdbcType=JdbcType.BIT)
    })
    Department selectByPrimaryKey(Integer iddepartment);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @UpdateProvider(type=DepartmentSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @UpdateProvider(type=DepartmentSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @UpdateProvider(type=DepartmentSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @Update({
        "update department",
        "set typecode = #{typecode,jdbcType=VARCHAR},",
          "typename = #{typename,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "priority = #{priority,jdbcType=VARCHAR},",
          "retired = #{retired,jdbcType=BIT}",
        "where iddepartment = #{iddepartment,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Department record);
}