package cn.edu.ken.mybatis.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import cn.edu.ken.mybatis.model.ContactInfo;
import cn.edu.ken.mybatis.model.ContactInfoExample.Criteria;
import cn.edu.ken.mybatis.model.ContactInfoExample.Criterion;
import cn.edu.ken.mybatis.model.ContactInfoExample;
import java.util.List;
import java.util.Map;

public class ContactInfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public String countByExample(ContactInfoExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("contactinfo");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public String deleteByExample(ContactInfoExample example) {
        BEGIN();
        DELETE_FROM("contactinfo");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public String insertSelective(ContactInfo record) {
        BEGIN();
        INSERT_INTO("contactinfo");
        
        if (record.getIdcontactinfo() != null) {
            VALUES("idcontactinfo", "#{idcontactinfo,jdbcType=INTEGER}");
        }
        
        if (record.getContactIdcontact() != null) {
            VALUES("contact_idcontact", "#{contactIdcontact,jdbcType=INTEGER}");
        }
        
        if (record.getFirstname() != null) {
            VALUES("firstname", "#{firstname,jdbcType=VARCHAR}");
        }
        
        if (record.getSecondname() != null) {
            VALUES("secondname", "#{secondname,jdbcType=VARCHAR}");
        }
        
        if (record.getAddress() != null) {
            VALUES("address", "#{address,jdbcType=VARCHAR}");
        }
        
        if (record.getState() != null) {
            VALUES("state", "#{state,jdbcType=VARCHAR}");
        }
        
        if (record.getCountry() != null) {
            VALUES("country", "#{country,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            VALUES("city", "#{city,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            VALUES("email", "#{email,jdbcType=VARCHAR}");
        }
        
        if (record.getTelephone() != null) {
            VALUES("telephone", "#{telephone,jdbcType=VARCHAR}");
        }
        
        if (record.getMobile() != null) {
            VALUES("mobile", "#{mobile,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public String selectByExample(ContactInfoExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("idcontactinfo");
        } else {
            SELECT("idcontactinfo");
        }
        SELECT("contact_idcontact");
        SELECT("firstname");
        SELECT("secondname");
        SELECT("address");
        SELECT("state");
        SELECT("country");
        SELECT("city");
        SELECT("email");
        SELECT("telephone");
        SELECT("mobile");
        FROM("contactinfo");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ContactInfo record = (ContactInfo) parameter.get("record");
        ContactInfoExample example = (ContactInfoExample) parameter.get("example");
        
        BEGIN();
        UPDATE("contactinfo");
        
        if (record.getIdcontactinfo() != null) {
            SET("idcontactinfo = #{record.idcontactinfo,jdbcType=INTEGER}");
        }
        
        if (record.getContactIdcontact() != null) {
            SET("contact_idcontact = #{record.contactIdcontact,jdbcType=INTEGER}");
        }
        
        if (record.getFirstname() != null) {
            SET("firstname = #{record.firstname,jdbcType=VARCHAR}");
        }
        
        if (record.getSecondname() != null) {
            SET("secondname = #{record.secondname,jdbcType=VARCHAR}");
        }
        
        if (record.getAddress() != null) {
            SET("address = #{record.address,jdbcType=VARCHAR}");
        }
        
        if (record.getState() != null) {
            SET("state = #{record.state,jdbcType=VARCHAR}");
        }
        
        if (record.getCountry() != null) {
            SET("country = #{record.country,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            SET("city = #{record.city,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            SET("email = #{record.email,jdbcType=VARCHAR}");
        }
        
        if (record.getTelephone() != null) {
            SET("telephone = #{record.telephone,jdbcType=VARCHAR}");
        }
        
        if (record.getMobile() != null) {
            SET("mobile = #{record.mobile,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("contactinfo");
        
        SET("idcontactinfo = #{record.idcontactinfo,jdbcType=INTEGER}");
        SET("contact_idcontact = #{record.contactIdcontact,jdbcType=INTEGER}");
        SET("firstname = #{record.firstname,jdbcType=VARCHAR}");
        SET("secondname = #{record.secondname,jdbcType=VARCHAR}");
        SET("address = #{record.address,jdbcType=VARCHAR}");
        SET("state = #{record.state,jdbcType=VARCHAR}");
        SET("country = #{record.country,jdbcType=VARCHAR}");
        SET("city = #{record.city,jdbcType=VARCHAR}");
        SET("email = #{record.email,jdbcType=VARCHAR}");
        SET("telephone = #{record.telephone,jdbcType=VARCHAR}");
        SET("mobile = #{record.mobile,jdbcType=VARCHAR}");
        
        ContactInfoExample example = (ContactInfoExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public String updateByPrimaryKeySelective(ContactInfo record) {
        BEGIN();
        UPDATE("contactinfo");
        
        if (record.getContactIdcontact() != null) {
            SET("contact_idcontact = #{contactIdcontact,jdbcType=INTEGER}");
        }
        
        if (record.getFirstname() != null) {
            SET("firstname = #{firstname,jdbcType=VARCHAR}");
        }
        
        if (record.getSecondname() != null) {
            SET("secondname = #{secondname,jdbcType=VARCHAR}");
        }
        
        if (record.getAddress() != null) {
            SET("address = #{address,jdbcType=VARCHAR}");
        }
        
        if (record.getState() != null) {
            SET("state = #{state,jdbcType=VARCHAR}");
        }
        
        if (record.getCountry() != null) {
            SET("country = #{country,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            SET("city = #{city,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            SET("email = #{email,jdbcType=VARCHAR}");
        }
        
        if (record.getTelephone() != null) {
            SET("telephone = #{telephone,jdbcType=VARCHAR}");
        }
        
        if (record.getMobile() != null) {
            SET("mobile = #{mobile,jdbcType=VARCHAR}");
        }
        
        WHERE("idcontactinfo = #{idcontactinfo,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    protected void applyWhere(ContactInfoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}