package cn.edu.ken.mybatis.model;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.iddepartment
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private Integer iddepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.typecode
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private String typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.typename
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.description
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.priority
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private String priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.retired
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    private Boolean retired;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.iddepartment
     *
     * @return the value of department.iddepartment
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public Integer getIddepartment() {
        return iddepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.iddepartment
     *
     * @param iddepartment the value for department.iddepartment
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setIddepartment(Integer iddepartment) {
        this.iddepartment = iddepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.typecode
     *
     * @return the value of department.typecode
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.typecode
     *
     * @param typecode the value for department.typecode
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode == null ? null : typecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.typename
     *
     * @return the value of department.typename
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.typename
     *
     * @param typename the value for department.typename
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.description
     *
     * @return the value of department.description
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.description
     *
     * @param description the value for department.description
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.priority
     *
     * @return the value of department.priority
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.priority
     *
     * @param priority the value for department.priority
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setPriority(String priority) {
        this.priority = priority == null ? null : priority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.retired
     *
     * @return the value of department.retired
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public Boolean getRetired() {
        return retired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.retired
     *
     * @param retired the value for department.retired
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    public void setRetired(Boolean retired) {
        this.retired = retired;
    }
}