-- MySQL Script generated by MySQL Workbench
-- Tue Sep 15 18:10:18 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ngoa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ngoa` ;

-- -----------------------------------------------------
-- Schema ngoa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ngoa` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `ngoa` ;

-- -----------------------------------------------------
-- Table `ngoa`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngoa`.`contact` ;

CREATE TABLE IF NOT EXISTS `ngoa`.`contact` (
  `idcontact` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idcontact`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngoa`.`activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngoa`.`activities` ;

CREATE TABLE IF NOT EXISTS `ngoa`.`activities` (
  `idactivities` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idactivities`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngoa`.`document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngoa`.`document` ;

CREATE TABLE IF NOT EXISTS `ngoa`.`document` (
  `iddocument` INT NOT NULL COMMENT '',
  PRIMARY KEY (`iddocument`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngoa`.`workcalendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngoa`.`workcalendar` ;

CREATE TABLE IF NOT EXISTS `ngoa`.`workcalendar` (
  `idworkcalendar` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idworkcalendar`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngoa`.`notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngoa`.`notes` ;

CREATE TABLE IF NOT EXISTS `ngoa`.`notes` (
  `idnotes` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idnotes`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngoa`.`meetings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngoa`.`meetings` ;

CREATE TABLE IF NOT EXISTS `ngoa`.`meetings` (
  `idmeetings` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idmeetings`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngoa`.`holiday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngoa`.`holiday` ;

CREATE TABLE IF NOT EXISTS `ngoa`.`holiday` (
  `idholiday` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idholiday`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngoa`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngoa`.`task` ;

CREATE TABLE IF NOT EXISTS `ngoa`.`task` (
  `idtask` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtask`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngoa`.`docnotes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngoa`.`docnotes` ;

CREATE TABLE IF NOT EXISTS `ngoa`.`docnotes` (
  `iddocnotes` INT NOT NULL COMMENT '',
  `notes_idnotes` INT NOT NULL COMMENT '',
  `document_iddocument` INT NOT NULL COMMENT '',
  `task_idtask` INT NOT NULL COMMENT '',
  PRIMARY KEY (`iddocnotes`)  COMMENT '',
  INDEX `fk_docnotes_notes_idx` (`notes_idnotes` ASC)  COMMENT '',
  INDEX `fk_docnotes_document1_idx` (`document_iddocument` ASC)  COMMENT '',
  INDEX `fk_docnotes_task1_idx` (`task_idtask` ASC)  COMMENT '',
  CONSTRAINT `fk_docnotes_notes`
    FOREIGN KEY (`notes_idnotes`)
    REFERENCES `ngoa`.`notes` (`idnotes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_docnotes_document1`
    FOREIGN KEY (`document_iddocument`)
    REFERENCES `ngoa`.`document` (`iddocument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_docnotes_task1`
    FOREIGN KEY (`task_idtask`)
    REFERENCES `ngoa`.`task` (`idtask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngoa`.`taskmemo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngoa`.`taskmemo` ;

CREATE TABLE IF NOT EXISTS `ngoa`.`taskmemo` (
  `task_idtask` INT NOT NULL COMMENT '',
  `notes_idnotes` INT NOT NULL COMMENT '',
  INDEX `fk_taskmemo_task1_idx` (`task_idtask` ASC)  COMMENT '',
  INDEX `fk_taskmemo_notes1_idx` (`notes_idnotes` ASC)  COMMENT '',
  CONSTRAINT `fk_taskmemo_task1`
    FOREIGN KEY (`task_idtask`)
    REFERENCES `ngoa`.`task` (`idtask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_taskmemo_notes1`
    FOREIGN KEY (`notes_idnotes`)
    REFERENCES `ngoa`.`notes` (`idnotes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
