package cn.edu.ken.mybatis.mapper;

import cn.edu.ken.mybatis.model.ContactInfo;
import cn.edu.ken.mybatis.model.ContactInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ContactInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @SelectProvider(type=ContactInfoSqlProvider.class, method="countByExample")
    int countByExample(ContactInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @DeleteProvider(type=ContactInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(ContactInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @Delete({
        "delete from contactinfo",
        "where idcontactinfo = #{idcontactinfo,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idcontactinfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @Insert({
        "insert into contactinfo (idcontactinfo, contact_idcontact, ",
        "firstname, secondname, ",
        "address, state, ",
        "country, city, email, ",
        "telephone, mobile)",
        "values (#{idcontactinfo,jdbcType=INTEGER}, #{contactIdcontact,jdbcType=INTEGER}, ",
        "#{firstname,jdbcType=VARCHAR}, #{secondname,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{state,jdbcType=VARCHAR}, ",
        "#{country,jdbcType=VARCHAR}, #{city,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{telephone,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR})"
    })
    int insert(ContactInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @InsertProvider(type=ContactInfoSqlProvider.class, method="insertSelective")
    int insertSelective(ContactInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @SelectProvider(type=ContactInfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="idcontactinfo", property="idcontactinfo", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="contact_idcontact", property="contactIdcontact", jdbcType=JdbcType.INTEGER),
        @Result(column="firstname", property="firstname", jdbcType=JdbcType.VARCHAR),
        @Result(column="secondname", property="secondname", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="state", property="state", jdbcType=JdbcType.VARCHAR),
        @Result(column="country", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="telephone", property="telephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR)
    })
    List<ContactInfo> selectByExample(ContactInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @Select({
        "select",
        "idcontactinfo, contact_idcontact, firstname, secondname, address, state, country, ",
        "city, email, telephone, mobile",
        "from contactinfo",
        "where idcontactinfo = #{idcontactinfo,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="idcontactinfo", property="idcontactinfo", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="contact_idcontact", property="contactIdcontact", jdbcType=JdbcType.INTEGER),
        @Result(column="firstname", property="firstname", jdbcType=JdbcType.VARCHAR),
        @Result(column="secondname", property="secondname", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="state", property="state", jdbcType=JdbcType.VARCHAR),
        @Result(column="country", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="telephone", property="telephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR)
    })
    ContactInfo selectByPrimaryKey(Integer idcontactinfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @UpdateProvider(type=ContactInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ContactInfo record, @Param("example") ContactInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @UpdateProvider(type=ContactInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ContactInfo record, @Param("example") ContactInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @UpdateProvider(type=ContactInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ContactInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactinfo
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    @Update({
        "update contactinfo",
        "set contact_idcontact = #{contactIdcontact,jdbcType=INTEGER},",
          "firstname = #{firstname,jdbcType=VARCHAR},",
          "secondname = #{secondname,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=VARCHAR},",
          "country = #{country,jdbcType=VARCHAR},",
          "city = #{city,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "telephone = #{telephone,jdbcType=VARCHAR},",
          "mobile = #{mobile,jdbcType=VARCHAR}",
        "where idcontactinfo = #{idcontactinfo,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ContactInfo record);
}