package cn.edu.ken.mybatis.mapper;

import cn.edu.ken.mybatis.model.Contact;
import cn.edu.ken.mybatis.model.ContactExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    @SelectProvider(type=ContactSqlProvider.class, method="countByExample")
    int countByExample(ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    @DeleteProvider(type=ContactSqlProvider.class, method="deleteByExample")
    int deleteByExample(ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    @Delete({
        "delete from contact",
        "where idcontact = #{idcontact,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idcontact);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    @Insert({
        "insert into contact (idcontact, meetings_idmeetings, ",
        "contacttype_idcontacttype, username, ",
        "password, userlocale, ",
        "usersetting, retired, ",
        "department_iddepartment)",
        "values (#{idcontact,jdbcType=INTEGER}, #{meetingsIdmeetings,jdbcType=INTEGER}, ",
        "#{contacttypeIdcontacttype,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{userlocale,jdbcType=VARCHAR}, ",
        "#{usersetting,jdbcType=VARCHAR}, #{retired,jdbcType=BIT}, ",
        "#{departmentIddepartment,jdbcType=INTEGER})"
    })
    int insert(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    @InsertProvider(type=ContactSqlProvider.class, method="insertSelective")
    int insertSelective(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    @SelectProvider(type=ContactSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="idcontact", property="idcontact", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="meetings_idmeetings", property="meetingsIdmeetings", jdbcType=JdbcType.INTEGER),
        @Result(column="contacttype_idcontacttype", property="contacttypeIdcontacttype", jdbcType=JdbcType.INTEGER),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="userlocale", property="userlocale", jdbcType=JdbcType.VARCHAR),
        @Result(column="usersetting", property="usersetting", jdbcType=JdbcType.VARCHAR),
        @Result(column="retired", property="retired", jdbcType=JdbcType.BIT),
        @Result(column="department_iddepartment", property="departmentIddepartment", jdbcType=JdbcType.INTEGER)
    })
    List<Contact> selectByExample(ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    @Select({
        "select",
        "idcontact, meetings_idmeetings, contacttype_idcontacttype, username, password, ",
        "userlocale, usersetting, retired, department_iddepartment",
        "from contact",
        "where idcontact = #{idcontact,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="idcontact", property="idcontact", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="meetings_idmeetings", property="meetingsIdmeetings", jdbcType=JdbcType.INTEGER),
        @Result(column="contacttype_idcontacttype", property="contacttypeIdcontacttype", jdbcType=JdbcType.INTEGER),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="userlocale", property="userlocale", jdbcType=JdbcType.VARCHAR),
        @Result(column="usersetting", property="usersetting", jdbcType=JdbcType.VARCHAR),
        @Result(column="retired", property="retired", jdbcType=JdbcType.BIT),
        @Result(column="department_iddepartment", property="departmentIddepartment", jdbcType=JdbcType.INTEGER)
    })
    Contact selectByPrimaryKey(Integer idcontact);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    @UpdateProvider(type=ContactSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Contact record, @Param("example") ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    @UpdateProvider(type=ContactSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Contact record, @Param("example") ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    @UpdateProvider(type=ContactSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    @Update({
        "update contact",
        "set meetings_idmeetings = #{meetingsIdmeetings,jdbcType=INTEGER},",
          "contacttype_idcontacttype = #{contacttypeIdcontacttype,jdbcType=INTEGER},",
          "username = #{username,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "userlocale = #{userlocale,jdbcType=VARCHAR},",
          "usersetting = #{usersetting,jdbcType=VARCHAR},",
          "retired = #{retired,jdbcType=BIT},",
          "department_iddepartment = #{departmentIddepartment,jdbcType=INTEGER}",
        "where idcontact = #{idcontact,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Contact record);
}