package cn.edu.ken.mybatis.mapper;

import cn.edu.ken.mybatis.model.Contact;
import cn.edu.ken.mybatis.model.ContactExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contact
     *
     * @mbggenerated Fri Sep 18 01:50:45 CST 2015
     */
    @SelectProvider(type=ContactSqlProvider.class, method="countByExample")
    int countByExample(ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contact
     *
     * @mbggenerated Fri Sep 18 01:50:45 CST 2015
     */
    @DeleteProvider(type=ContactSqlProvider.class, method="deleteByExample")
    int deleteByExample(ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contact
     *
     * @mbggenerated Fri Sep 18 01:50:45 CST 2015
     */
    @Delete({
        "delete from Contact",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contact
     *
     * @mbggenerated Fri Sep 18 01:50:45 CST 2015
     */
    @Insert({
        "insert into Contact (id, contactname, ",
        "age)",
        "values (#{id,jdbcType=INTEGER}, #{contactname,jdbcType=VARCHAR}, ",
        "#{age,jdbcType=INTEGER})"
    })
    int insert(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contact
     *
     * @mbggenerated Fri Sep 18 01:50:45 CST 2015
     */
    @InsertProvider(type=ContactSqlProvider.class, method="insertSelective")
    int insertSelective(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contact
     *
     * @mbggenerated Fri Sep 18 01:50:45 CST 2015
     */
    @SelectProvider(type=ContactSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="contactname", property="contactname", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.INTEGER)
    })
    List<Contact> selectByExample(ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contact
     *
     * @mbggenerated Fri Sep 18 01:50:45 CST 2015
     */
    @Select({
        "select",
        "id, contactname, age",
        "from Contact",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="contactname", property="contactname", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.INTEGER)
    })
    Contact selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contact
     *
     * @mbggenerated Fri Sep 18 01:50:45 CST 2015
     */
    @UpdateProvider(type=ContactSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Contact record, @Param("example") ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contact
     *
     * @mbggenerated Fri Sep 18 01:50:45 CST 2015
     */
    @UpdateProvider(type=ContactSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Contact record, @Param("example") ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contact
     *
     * @mbggenerated Fri Sep 18 01:50:45 CST 2015
     */
    @UpdateProvider(type=ContactSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contact
     *
     * @mbggenerated Fri Sep 18 01:50:45 CST 2015
     */
    @Update({
        "update Contact",
        "set contactname = #{contactname,jdbcType=VARCHAR},",
          "age = #{age,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Contact record);
}