package cn.edu.ken.mybatis.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import cn.edu.ken.mybatis.model.Contact;
import cn.edu.ken.mybatis.model.ContactExample.Criteria;
import cn.edu.ken.mybatis.model.ContactExample.Criterion;
import cn.edu.ken.mybatis.model.ContactExample;
import java.util.List;
import java.util.Map;

public class ContactSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    public String countByExample(ContactExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("contact");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    public String deleteByExample(ContactExample example) {
        BEGIN();
        DELETE_FROM("contact");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    public String insertSelective(Contact record) {
        BEGIN();
        INSERT_INTO("contact");
        
        if (record.getIdcontact() != null) {
            VALUES("idcontact", "#{idcontact,jdbcType=INTEGER}");
        }
        
        if (record.getMeetingsIdmeetings() != null) {
            VALUES("meetings_idmeetings", "#{meetingsIdmeetings,jdbcType=INTEGER}");
        }
        
        if (record.getContacttypeIdcontacttype() != null) {
            VALUES("contacttype_idcontacttype", "#{contacttypeIdcontacttype,jdbcType=INTEGER}");
        }
        
        if (record.getUsername() != null) {
            VALUES("username", "#{username,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            VALUES("password", "#{password,jdbcType=VARCHAR}");
        }
        
        if (record.getUserlocale() != null) {
            VALUES("userlocale", "#{userlocale,jdbcType=VARCHAR}");
        }
        
        if (record.getUsersetting() != null) {
            VALUES("usersetting", "#{usersetting,jdbcType=VARCHAR}");
        }
        
        if (record.getRetired() != null) {
            VALUES("retired", "#{retired,jdbcType=BIT}");
        }
        
        if (record.getDepartmentIddepartment() != null) {
            VALUES("department_iddepartment", "#{departmentIddepartment,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    public String selectByExample(ContactExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("idcontact");
        } else {
            SELECT("idcontact");
        }
        SELECT("meetings_idmeetings");
        SELECT("contacttype_idcontacttype");
        SELECT("username");
        SELECT("password");
        SELECT("userlocale");
        SELECT("usersetting");
        SELECT("retired");
        SELECT("department_iddepartment");
        FROM("contact");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Contact record = (Contact) parameter.get("record");
        ContactExample example = (ContactExample) parameter.get("example");
        
        BEGIN();
        UPDATE("contact");
        
        if (record.getIdcontact() != null) {
            SET("idcontact = #{record.idcontact,jdbcType=INTEGER}");
        }
        
        if (record.getMeetingsIdmeetings() != null) {
            SET("meetings_idmeetings = #{record.meetingsIdmeetings,jdbcType=INTEGER}");
        }
        
        if (record.getContacttypeIdcontacttype() != null) {
            SET("contacttype_idcontacttype = #{record.contacttypeIdcontacttype,jdbcType=INTEGER}");
        }
        
        if (record.getUsername() != null) {
            SET("username = #{record.username,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            SET("password = #{record.password,jdbcType=VARCHAR}");
        }
        
        if (record.getUserlocale() != null) {
            SET("userlocale = #{record.userlocale,jdbcType=VARCHAR}");
        }
        
        if (record.getUsersetting() != null) {
            SET("usersetting = #{record.usersetting,jdbcType=VARCHAR}");
        }
        
        if (record.getRetired() != null) {
            SET("retired = #{record.retired,jdbcType=BIT}");
        }
        
        if (record.getDepartmentIddepartment() != null) {
            SET("department_iddepartment = #{record.departmentIddepartment,jdbcType=INTEGER}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("contact");
        
        SET("idcontact = #{record.idcontact,jdbcType=INTEGER}");
        SET("meetings_idmeetings = #{record.meetingsIdmeetings,jdbcType=INTEGER}");
        SET("contacttype_idcontacttype = #{record.contacttypeIdcontacttype,jdbcType=INTEGER}");
        SET("username = #{record.username,jdbcType=VARCHAR}");
        SET("password = #{record.password,jdbcType=VARCHAR}");
        SET("userlocale = #{record.userlocale,jdbcType=VARCHAR}");
        SET("usersetting = #{record.usersetting,jdbcType=VARCHAR}");
        SET("retired = #{record.retired,jdbcType=BIT}");
        SET("department_iddepartment = #{record.departmentIddepartment,jdbcType=INTEGER}");
        
        ContactExample example = (ContactExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    public String updateByPrimaryKeySelective(Contact record) {
        BEGIN();
        UPDATE("contact");
        
        if (record.getMeetingsIdmeetings() != null) {
            SET("meetings_idmeetings = #{meetingsIdmeetings,jdbcType=INTEGER}");
        }
        
        if (record.getContacttypeIdcontacttype() != null) {
            SET("contacttype_idcontacttype = #{contacttypeIdcontacttype,jdbcType=INTEGER}");
        }
        
        if (record.getUsername() != null) {
            SET("username = #{username,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            SET("password = #{password,jdbcType=VARCHAR}");
        }
        
        if (record.getUserlocale() != null) {
            SET("userlocale = #{userlocale,jdbcType=VARCHAR}");
        }
        
        if (record.getUsersetting() != null) {
            SET("usersetting = #{usersetting,jdbcType=VARCHAR}");
        }
        
        if (record.getRetired() != null) {
            SET("retired = #{retired,jdbcType=BIT}");
        }
        
        if (record.getDepartmentIddepartment() != null) {
            SET("department_iddepartment = #{departmentIddepartment,jdbcType=INTEGER}");
        }
        
        WHERE("idcontact = #{idcontact,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Sep 22 11:29:48 CST 2015
     */
    protected void applyWhere(ContactExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}