package cn.edu.ken.mybatis.model;

public class Contact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contact.id
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contact.username
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contact.password
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contact.age
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contact.firstname
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    private String firstname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contact.secondname
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    private String secondname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contact.selfcontent
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    private String selfcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contact.id
     *
     * @return the value of Contact.id
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contact.id
     *
     * @param id the value for Contact.id
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contact.username
     *
     * @return the value of Contact.username
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contact.username
     *
     * @param username the value for Contact.username
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contact.password
     *
     * @return the value of Contact.password
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contact.password
     *
     * @param password the value for Contact.password
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contact.age
     *
     * @return the value of Contact.age
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contact.age
     *
     * @param age the value for Contact.age
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contact.firstname
     *
     * @return the value of Contact.firstname
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contact.firstname
     *
     * @param firstname the value for Contact.firstname
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contact.secondname
     *
     * @return the value of Contact.secondname
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    public String getSecondname() {
        return secondname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contact.secondname
     *
     * @param secondname the value for Contact.secondname
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    public void setSecondname(String secondname) {
        this.secondname = secondname == null ? null : secondname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contact.selfcontent
     *
     * @return the value of Contact.selfcontent
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    public String getSelfcontent() {
        return selfcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contact.selfcontent
     *
     * @param selfcontent the value for Contact.selfcontent
     *
     * @mbggenerated Sat Sep 19 10:06:54 CST 2015
     */
    public void setSelfcontent(String selfcontent) {
        this.selfcontent = selfcontent == null ? null : selfcontent.trim();
    }
}