package cn.edu.ken.mybatis.mapper;

import cn.edu.ken.mybatis.model.ContactType;
import cn.edu.ken.mybatis.model.ContactTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContactTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacttype
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    int countByExample(ContactTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacttype
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    int deleteByExample(ContactTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacttype
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    int deleteByPrimaryKey(Integer idcontacttype);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacttype
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    int insert(ContactType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacttype
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    int insertSelective(ContactType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacttype
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    List<ContactType> selectByExample(ContactTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacttype
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    ContactType selectByPrimaryKey(Integer idcontacttype);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacttype
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    int updateByExampleSelective(@Param("record") ContactType record, @Param("example") ContactTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacttype
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    int updateByExample(@Param("record") ContactType record, @Param("example") ContactTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacttype
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    int updateByPrimaryKeySelective(ContactType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contacttype
     *
     * @mbggenerated Sun Sep 27 11:02:32 CST 2015
     */
    int updateByPrimaryKey(ContactType record);
}