package cn.edu.ken.mybatis.model;

public class ContactType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contacttype.idcontacttype
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    private Integer idcontacttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contacttype.typecode
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    private String typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contacttype.typename
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contacttype.description
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contacttype.priority
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    private Byte priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contacttype.retired
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    private Boolean retired;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contacttype.idcontacttype
     *
     * @return the value of contacttype.idcontacttype
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public Integer getIdcontacttype() {
        return idcontacttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contacttype.idcontacttype
     *
     * @param idcontacttype the value for contacttype.idcontacttype
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public void setIdcontacttype(Integer idcontacttype) {
        this.idcontacttype = idcontacttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contacttype.typecode
     *
     * @return the value of contacttype.typecode
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contacttype.typecode
     *
     * @param typecode the value for contacttype.typecode
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode == null ? null : typecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contacttype.typename
     *
     * @return the value of contacttype.typename
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contacttype.typename
     *
     * @param typename the value for contacttype.typename
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contacttype.description
     *
     * @return the value of contacttype.description
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contacttype.description
     *
     * @param description the value for contacttype.description
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contacttype.priority
     *
     * @return the value of contacttype.priority
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public Byte getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contacttype.priority
     *
     * @param priority the value for contacttype.priority
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public void setPriority(Byte priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contacttype.retired
     *
     * @return the value of contacttype.retired
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public Boolean getRetired() {
        return retired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contacttype.retired
     *
     * @param retired the value for contacttype.retired
     *
     * @mbggenerated Tue Sep 22 14:56:15 CST 2015
     */
    public void setRetired(Boolean retired) {
        this.retired = retired;
    }
}